# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '0':
        pose: SwarmNode0/pose
        pose2d: SwarmNode0/ground_pose
        child_frame_id: body
        parent_frame_id: world
    '1':
        pose: SwarmNode1/pose
        pose2d: SwarmNode1/ground_pose
        child_frame_id: body
        parent_frame_id: world
    '2':
        pose: SwarmNode2/pose
        pose2d: SwarmNode2/ground_pose
        child_frame_id: body
        parent_frame_id: world
    '3':
        pose: SwarmNode3/pose
        pose2d: SwarmNode3/ground_pose
        child_frame_id: body
        parent_frame_id: world
    '4':
        pose: SwarmNode4/pose
        pose2d: SwarmNode4/ground_pose
        child_frame_id: body
        parent_frame_id: world
    '5':
        pose: SwarmNode5/pose
        pose2d: SwarmNode5/ground_pose
        child_frame_id: body
        parent_frame_id: world
